
set(target "BlackHole")
set(working_dir "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI")
set(src_and_dest_list
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/Main.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/Main.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/BlackholeLargePreview.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/BlackholeLargePreview.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/BlackholePreview.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/BlackholePreview.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/BlackholePreviewArea.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/BlackholePreviewArea.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EAlertDialog.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EAlertDialog.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EAvatar.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EAvatar.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EBlurCard.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EBlurCard.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EButton.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EButton.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EDrawer.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EDrawer.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EDropDown.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EDropDown.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EList.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EList.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/ESlider.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/ESlider.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/ESwitchButton.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/ESwitchButton.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/ETheme.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/ETheme.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/ETimeDisplay.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/ETimeDisplay.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/components/EToast.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/components/EToast.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/pages/AdvancedConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/pages/AdvancedConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/pages/BlackholeConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/pages/BlackholeConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/pages/IdleListConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/pages/IdleListConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/Blakhole_UI/pages/ScheduleConfig.qml"
    "D:/Projects/ghostty-blackhole-main-main/build_qt/BlakholeUI/pages/ScheduleConfig.qml"

)
set(timestamp_file "D:/Projects/ghostty-blackhole-main-main/build_qt/.qt/BlackHole_qml.txt")
